version: 2

sphinx:
  configuration: docs/conf.py

build:
    image: latest

python:
    version: 3.7
    install:
      - requirements: deocs/requirements.txt
      - method: pip
        path: .
        extra_requirements:
           - docs
      - method: setuptools
        path: .

