version: '{branch}-{build}'
build: off
cache:
  - '%LOCALAPPDATA%\pip\Cache'
init:
  - ps: echo $env:TOXENV
  - ps: ls C:\Python*
#install:
#  - r'C:\Python36-x64\Scripts\virtualenv --version'
#  - r'C:\Python36-x64\Scripts\easy_install --version'
#  - r'C:\Python36-x64\Scripts\pip --version'
#  - r'C:\Python36-x64\Scripts\tox --version'
#  - r'C:\Python36-x64\Scripts\pip install pysight'
test_script:
  - '%WITH_COMPILER% %PYTHON_HOME%\Scripts\tox'
on_failure:
  - ps: dir "env:"
  - ps: get-content .tox\*\log\*
artifacts:
  - path: dist\*

### To enable remote debugging uncomment this (also, see: http://www.appveyor.com/docs/how-to/rdp-to-build-worker):
# on_finish:
#   - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
