[package]
name = 'lst_parser'
version = "0.1.0"
authors = ["Hagai Har-Gil <hagaihargil@protonmail.com>"]

[lib]
crate-type = ["cdylib"]

[dependencies]
filebuffer = "0.3"
bitreader = "0.3"
failure = "0.1"
data-encoding = "2.1"

[dependencies.pyo3]
version = "0.2"
default-features = false
