[tool.black]
py36 = true
line-length = 120
target_version = ['py36', 'py37']
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''