[package]
name = 'pysight'
version = "0.1.0"
authors = ["Hagai Har-Gil <hagaihargil@protonmail.com>"]

[lib]
name = 'pysight'
crate-type = ["cdylib"]

[dependencies]
filebuffer = "0.3"
bitreader = "0.3"
failure = "0.1"
libc = "0.2"

[build-dependencies]
cbindgen = "0.5"
